/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2012-09-11 02:55:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class smokvicaKornati_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html version=\"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta\r\n");
      out.write("\thttp-equiv=\"Content - Type\"\r\n");
      out.write("\tcontent=\"text/html\"\r\n");
      out.write("/>\r\n");
      out.write("<title>APARTMANI - OTOK MURTER | Murter | Murtersko otocje |\r\n");
      out.write("\tKornatsko otocje | Kornati |</title>\r\n");
      out.write("\r\n");
      out.write("<meta\r\n");
      out.write("\tname=\"Description\"\r\n");
      out.write("\tcontent=\"Povijesna bastina na otoku Murteru datira jos iz doba Liburna.\"\r\n");
      out.write(">\r\n");
      out.write("<meta\r\n");
      out.write("\tname=\"Keywords\"\r\n");
      out.write("\tcontent=\"Otok Murter, Murtersko otocje, Kornatsko otocje, Kornati\"\r\n");
      out.write(">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"css/global.css\"\r\n");
      out.write("\trel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\"\r\n");
      out.write(">\r\n");
      out.write("<!--  <link href=\"css/layout.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write(" link href=\"CSS/jquery.fancybox.css\" rel=\"stylesheet\" media=\"screen\"\r\n");
      out.write(" \r\n");
      out.write(" <script type=\"text/javascript\" src=\"scripts/jquery-1.7.2.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"scripts/jquery.bxSlider.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"scripts/jquery.fancybox.pack.js\"></script>\r\n");
      out.write(" \r\n");
      out.write(" <script type=\"text/javascript\" src=\"scripts/jquery.galleryview-2.1.1.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"scripts/jquery.timers-1.1.2.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"scripts/jquery.easing.1.3.js\"></script>\r\n");
      out.write(" -->\r\n");
      out.write("<!--link href=\"CSS/galleryview.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\"-->\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\ttype=\"text/javascript\"\r\n");
      out.write("\tsrc=\"scripts/swfobject.js\"\r\n");
      out.write("></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"home\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"header\">\r\n");
      out.write("\t\t\t<div class=\"header_left\">\r\n");
      out.write("\t\t\t\t<div id=\"site_logo\">\r\n");
      out.write("\t\t\t\t\t<span>Obitelj Purnikovic - Arso i Masha Putnikovic</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"header_right\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/illustration/\"\r\n");
      out.write("\t\t\t\t\t\tid=\"nav_01\"\r\n");
      out.write("\t\t\t\t\t>Illustration</a>\r\n");
      out.write("\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/about/\"\r\n");
      out.write("\t\t\t\t\t\tid=\"nav_02\"\r\n");
      out.write("\t\t\t\t\t>About</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/contact/\"\r\n");
      out.write("\t\t\t\t\t\tid=\"nav_03\"\r\n");
      out.write("\t\t\t\t\t>Contact</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"links_2\">\r\n");
      out.write("\t\t\t\t<a href=\"https://www.facebook.com/zlanusic\"><img\r\n");
      out.write("\t\t\t\t\talt=\"rss feed\"\r\n");
      out.write("\t\t\t\t\tsrc=\"css/images/Links_pics/followFacebook.jpg\"/>\r\n");
      out.write("\t\t\t\t</a> <a href=\"https://twitter.com/zlanusic\"><img\r\n");
      out.write("\t\t\t\t\talt=\"rss feed\"\r\n");
      out.write("\t\t\t\t\tsrc=\"css/images/Links_pics/twitter_link.jpg\"/>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\"></div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
